import React, { useState, useEffect } from "react"
import Main from "./components/Main"

const App = () => {
	const [params, setParams] = useState<any>([])
	// const [loggedin, setLoggedin] = useState<string>("NOT_ATHOURIZED")

	// const handleLogin = () => {
	// 	if (params.access_token) {
	// 		setLoggedin("AUTHORIZED")
	// 		return (
	// 			<a href="http://localhost:8888">
	// 				<button> Login to Spotify</button>
	// 			</a>
	// 		)
	// 	} else {
	// 		return (
	// 			<a href="http://localhost:8888">
	// 				<button> Logout of Spotify</button>
	// 			</a>
	// 		)
	// 	}
	// }

	// grabs authentication key from URL generated by the backend
	const getHashParams = () => {
		var hashParams: any = {}
		var e,
			r = /([^&;=]+)=?([^&;]*)/g,
			q = window.location.hash.substring(1)
		while ((e = r.exec(q))) {
			hashParams[e[1]] = decodeURIComponent(e[2])
		}
		setParams(hashParams)
	}

	useEffect(() => {
		getHashParams()
	}, [])

	return (
		<div>
			<a href="http://localhost:8888">
				<button> Login to Spotify</button>
			</a>
			<Main getParams={params.access_token} />
		</div>
	)
}

export default App
