import React, { useState, useEffect } from "react"
import Main from "./components/Main"
import Login from "./components/Login"
import { ExtractToken } from "./components/Spotify"

const App = () => {
	const [params, setParams] = useState<any>([])
	const [loggedin, setLoggedin] = useState<string>("NOT_ATHOURIZED")
	const [token, setToken] = useState(null)

	useEffect(() => {
		const hash = ExtractToken()
		window.location.hash = ""
		const _token = hash.access_token
		if (_token) {
			setToken(_token)
		}
	})

	const handleLogin = () => {
		if (params.access_token) {
			setLoggedin("AUTHORIZED")
			return (
				<a href="http://localhost:8888">
					<button> Login to Spotify</button>
				</a>
			)
		} else {
			return (
				<a href="http://localhost:8888">
					<button> Logout of Spotify</button>
				</a>
			)
		}
	}

	// grabs authentication key from URL generated by the backend
	const getHashParams = () => {
		var hashParams: any = {}
		var e,
			r = /([^&;=]+)=?([^&;]*)/g,
			q = window.location.hash.substring(1)
		while ((e = r.exec(q))) {
			hashParams[e[1]] = decodeURIComponent(e[2])
		}
		setParams(hashParams)
	}

	useEffect(() => {
		getHashParams()
	}, [])

	return (
		<div>
			{token ? <h1>Successfully logged it</h1> : <Login />}
			<a href="http://localhost:8888">
				<button> Login to Spotify</button>
			</a>
			<Main getParams={params.access_token} />
		</div>
	)
}

export default App
